config/routes.rb
Rails.application.routes.draw do
  resources :carts
  resources :cart_items
	resources :services do
		get :get_service, on: :member
	end
  devise_for :users
  root to: "homes#index"
  resources :panels

  get '/search' => 'services#search', :as => 'search_page'
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :service
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, uniqueness: true
	has_many :services
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/role.rb
class Role < ApplicationRecord 
	validates :name, presence: true, uniqueness: true
	has_one :user
end

app/models/service.rb
class Service < ApplicationRecord
	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :cart_items
	belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  def current_cart(user)
    if user.cart.present?
      cart = user.cart
    else
      cart = user.create_cart
    end
    cart
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end  

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	skip_before_action :verify_authenticity_token, only: [:create]
  def index
    if current_user.present?
  	@cart = current_user.cart
  	@users = User.all
  	@cart_items = @cart.cart_items
    end
  end

  def create
    # binding.pry
  	if current_user.present?
      @cart = current_cart(current_user)
  		if @cart.cart_items.find_by_service_id(params[:service_dashboard_id]).blank?
  			@cart_items = @cart.cart_items.new(service_id: params[:service_dashboard_id])
  			if @cart_items.save
          redirect_back(fallback_location: services_path)
  			 	flash[:notice] = 'Item Added Successfully'
  			end
  		else
        redirect_back(fallback_location: services_path)
  			flash[:notice] = 'Item Already added'
  		end
  		respond_to do |format|
  			format.js{}
  		end
  	else
  		redirect_to new_user_session_path
      flash[:notice] = 'Please login first'
  	end
  end

  def destroy
  @cartitem = CartItem.find(params[:id])
    if @cartitem.destroy
      flash[:notice] = "Product deleted"
      redirect_to carts_path
    else
      flash[:alert] = "Error deleting product!"
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
    if current_user.present?
    @cart = current_user.cart
    @users = User.all
    @cart_items = @cart.cart_items
    end   
  end

  def new
  	@category = Category.new
    authorize @category
    if current_user.present?
    @cart = current_user.cart
    @users = User.all
    @cart_items = @cart.cart_items
    end
  end

  def create
  	@category = Category.new(cat_params)
  	if @category.save
      authorize @category
  		redirect_to categories_path
  	else
  		flash[:notice] = "Error While creating Category"
  	end
  end

  def destroy
    @category = Category.find(params[:id])
      authorize @category
    if @category.destroy
      redirect_to categories_path
    else
      flash[:alert] = "Error Deleting category"
    end
  end

  private

  def cat_params
  	params.require(:category).permit(:name, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  	@users = User.all
  	@categories = Category.all
  	if current_user.present?
  		@cart = current_cart(current_user)
  	end
    if current_user.present?
    @cart = current_user.cart
    @users = User.all
    @cart_items = @cart.cart_items
    end  	
  end
end

app/controllers/panels_controller.rb
class PanelsController < ApplicationController
  def index
  	@users = User.all
    if current_user.present?
    @cart = current_user.cart
    @users = User.all
    @cart_items = @cart.cart_items
    end
  end

  def new
  	@user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
  	if @user.save
      authorize @user
  		redirect_to panels_path
  	else
  		flash[:notice] = "User Not Created"
  	end
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if params[:format] == "1"
      @user.role_id = 2
      @user.save
      redirect_to panels_path
    else
      @user.role_id = 1
      @user.save
      redirect_to panels_path
    end
  end

  def destroy
  	@user = User.find(params[:id])
      authorize @user
  	if @user.destroy
  		redirect_to panels_path
  	else
  		flash[:notice] = "Error deleting User!!"
  	end
  end

  private

  def user_params
  	params.permit(:data)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
    @categories = Category.all
    if current_user.present?
    @cart = current_user.cart
    @users = User.all
    @cart_items = @cart.cart_items
    end
  end

  def new
    @service = Service.new
    authorize @service
    if current_user.present?
    @cart = current_user.cart
    @users = User.all
    @cart_items = @cart.cart_items
    end   
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      authorize @service
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @services = Service.where(:category_id => params[:id].to_i)
    if current_user.present?
    @cart = current_user.cart
    @users = User.all
    @cart_items = @cart.cart_items
    end 
  end

  def destroy
    @service = Service.find(params[:id])
      authorize @service
    if @service.destroy
      redirect_to services_path
    else
      flash[:alert] = "Error Deleting Product"
    end
  end

  def get_service
    # binding.pry
    @service = Service.find(params[:id])
    respond_to do |format|
      format.html
      format.js
     end
  end

  def search  
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      # @services = Service.all.where("lower(name) LIKE :search", search: @parameter) 
      @results = Service.all.where("lower(title) LIKE :search", search: "%#{@parameter}%") 
    end  
  end

  private

  def service_params
    params.require(:service).permit(:title, :detail, :price, :image, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def service_dashboard_img(service)
		if service.image.present?
	    image_tag service.image.url
	  else
	    image_tag 'default_service.png'
	  end
	end

	def category_dashboard_img(c)
		if c.image.present?
	    image_tag c.image.url
	  else
	    image_tag 'default_category.png'
	  end
	end

	def cart_item_dashboard_img(ci)
		if ci.service.image.present?
	    	image_tag ci.service.image.url
	  else
	    image_tag 'default_category.png'
	  end
	end
	
	def search_dashboard_img(result)
		if result.image.present?
	    image_tag result.image.url
	  else
	    image_tag 'default_category.png'
	  end
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/panels_helper.rb
module PanelsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/carts/index.html.erb
<% if current_user.nil? %>
	<h2>Please login first for adding services </h2>
<% end %>

<% if @cart_items.nil? || @cart_items.empty? %>
	<h1> Your Cart is Empty </h1>
<% else %>
<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <% current_user.present? && @cart_items.each do |ci| %>
        <!-- shop -->
        <div class="col-md-4 col-xs-6">
          <div class="shop">
            <div class="shop-img">
              <%= cart_item_dashboard_img(ci) %>
            </div>
            <div class="shop-body">
              <h3><%= ci.service.title %></h3>
              <h4>₹<%= ci.service.price %></h4>
              <%= button_to 'Remove', cart_path(ci), class: 'add-to-cart-btn delete btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
            </div>
          </div>
        </div>
        <!-- /shop -->  
      <% end %>   
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /SECTION -->
<% end %>

app/views/categories/index.html.erb
<!-- SECTION -->
<div class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<% @categories.each do |c| %>
				<!-- shop -->
				<div class="col-md-4 col-xs-6">
					<div class="shop">
						<div class="shop-img">
							<%= category_dashboard_img(c) %>
						</div>
						<div class="shop-body">
							<h3><%= c.name %></h3><br>
							<% if current_user.role_id == 1 %>
					  		<%= button_to 'Remove', category_path(c), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %>
					  	<% end %>
						</div>
					</div>
				</div>
				<!-- /shop -->	
			<% end %>		
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->

app/views/categories/new.html.erb
<%= form_for @category do |cat| %>
	<div class="form-group">
	<%= cat.label :name %>
	<%=cat.text_field :name %>
	</div>
  <div class="form-group">
    <%= cat.label :image %>
    <%= cat.file_field :image, class: 'form-control' %>
  </div>
	<div class="form-group">
	<%= cat.submit %>
	</div>
<% end %>

app/views/homes/index.html.erb
<!-- SECTION -->
<div class="section">
	<!-- container -->
	<div class="container">
		<!-- row -->
		<div class="row">
			<% @categories.each do |c| %>
				<!-- shop -->
				<div class="col-md-4 col-xs-6">
					<div class="shop">
						<div class="shop-img">
							<!-- <img src="/assets/shop01.png" alt=""> --><%= category_dashboard_img(c) %>
						</div>
						<div class="shop-body">
							<%= link_to c.name ,service_path(c), class: "cta-btn" %> <i class="fa fa-arrow-circle-right"></i>
						</div>
					</div>
				</div>
				<!-- /shop -->	
			<% end %>		
		</div>
		<!-- /row -->
	</div>
	<!-- /container -->
</div>
<!-- /SECTION -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urban</title>
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">
    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="/assets/bootstrap.min.css"/>
    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="/assets/slick.css"/>
    <link type="text/css" rel="stylesheet" href="/assets/slick-theme.css"/>
    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="/assets/nouislider.min.css"/>
    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="/assets/font-awesome.min.css">
    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="/assets/style.css"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%# if current_user.present? %>
      <%= render 'shared/header'%>
    <%# end %>
      <%= yield %>
    <%# if current_user.present? %>
      <%= render 'shared/footer'%>
    <%# end %>
  </body>
  <!-- jQuery Plugins -->
    <script src="/assets/jquery.min.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/slick.min.js"></script>
    <script src="/assets/nouislider.min.js"></script>
    <script src="/assets/jquery.zoom.min.js"></script>
    <script src="/assets/main.js"></script>
</html>
  <!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> -->
  <!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->

app/views/panels/index.html.erb
<body class = "user-body">
<table>
  <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      <th scope="col">Manage</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= collection_select(:user, :role_id, Role.all, :id, :name, {:selected => user.role_id}) %></td>
      <td><%= link_to "Change Role", panel_path(user,user.role_id ), :method=> :put %></td>    
      <td><%= link_to 'Destroy', panel_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</body>

app/views/services/_popup_model_content.html.erb
<% if service.present? %>
  <div class="modal-header">
    <h4 class="modal-title" id="myModalLabel"><%= service.title %></h4>
    <button type="button" class="close" data-dismiss="modal">x</button>
  </div>
  <div class="modal-body"><b>Service Details :-</b></br>
    <%= service.detail %>
  </div>
  <div class="modal-body"><b>Service Charges :-</b>
    <%= service.price %>
  </div>
  <div class="modal-body"><b>Category Name :-</b>
    <%= service.category.name %>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary">Save</button>
  </div>
<% end %>

app/views/services/_service_detail_popup_model.erb
<!-- Modal -->
<!-- <div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id ="service-modal-body">
        <%#= render 'popup_model_content' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div> -->

<div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">      
     <%= render 'services/popup_model_content', service: @service || nil %>
    </div>
  </div>
</div>

app/views/services/get_service.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'popup_model_content', service: @service) %>");
$("#modal-window").modal();

app/views/services/index.html.erb
<!-- heroku git:remote -a sid-login-app -->
<!-- https://www.loggly.com/blog/analyzing-heroku-router-logs-with-solarwinds-loggly/ -->
<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <% @services.each do |service| %>
        <!-- shop -->
        <div class="col-md-4 col-xs-6">
          <div class="shop">
            <div class="shop-img">
              <%= service_dashboard_img(service) %>
            </div>
            <div class="shop-body">
              <h3><%= service.title %></h3>
              <h4>₹<%= service.price %></h4>
              <%= link_to 'Details', get_service_service_path(service),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn active'}  %>
              <% if current_user.role_id == 1 %>      
                <div class="desc">
                  <%= button_to 'Remove', service_path(service), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %>
                </div>
              <% end %>
              <div class="desc"><%= link_to "Add Cart",'javascript:;',id: "service_#{service.id}", class: " btn-sm add-service-id" %></div>
            </div>
          </div>
        </div>
        <!-- /shop -->  
      <% end %>   
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /SECTION -->
<%= render 'services/service_detail_popup_model', services: @services %>

<script type="text/javascript">
  $(document).ready(function(){
    $(".add-service-id").on('click', function(){
      var service_dashboard_id = $(this).attr('id')
      var service_dashboard_id = service_dashboard_id.split('service_')[1]
      $.ajax({
        url: "<%= carts_path %>",
        type: "POST",
        data: {
          service_dashboard_id: service_dashboard_id
        }
      });
    });
  });
</script>

app/views/services/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>
<%= form_for @service, html: { multipart: true } do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@service.errors.count, "error")} prohibited this service from being saved:" %>
      </h2>
      <ul>
        <% @service.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
  </div>
<% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :detail %>
    <%= f.text_area :detail, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= collection_select(:service, :category_id, Category.all, :id, :name, :prompt => true )%>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Service', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/services/search.html.erb
<body class = "popup-body">
  <% @results.each do |result| %>
    <div class="gallery">
      <a target="_blank">
        <%= service_dashboard_img(result) %>
      </a>
      <div class="desc"><%= result.title %></div>
      <div class="desc">
        <%= link_to 'Details', get_service_service_path(result),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg'}  %>
      </div>
      <% if current_user.present? && current_user.role_id == 1 %>      
        <div class="desc">
          <%= button_to 'Remove', service_path(service), class: 'add-to-cart-btn delete', method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
      <% end %>
      <div class="desc"><%= link_to "Add Cart",'javascript:;',id: "service_#{result.id}", class: "add-service-id" %></div>
    </div>
  <% end %>
</body>
<%= render 'services/service_detail_popup_model', services: @services %>

<script type="text/javascript">
  $(document).ready(function(){
    $(".add-service-id").on('click', function(){
      var service_dashboard_id = $(this).attr('id')
      var service_dashboard_id = service_dashboard_id.split('service_')[1]
      $.ajax({
        url: "<%= carts_path %>",
        type: "POST",
        data: {
          service_dashboard_id: service_dashboard_id
        }
      });
    });
  });
</script>

app/views/services/show.html.erb
<!-- heroku git:remote -a sid-login-app -->
<!-- https://www.loggly.com/blog/analyzing-heroku-router-logs-with-solarwinds-loggly/ -->
<!-- SECTION -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <% @services.each do |service| %>
        <!-- shop -->
        <div class="col-md-4 col-xs-6">
          <div class="shop">
            <div class="shop-img">
              <%= service_dashboard_img(service) %>
            </div>
            <div class="shop-body">
              <h3><%= service.title %></h3>
              <h4>₹<%= service.price %></h4>
              <%= link_to 'Details', get_service_service_path(service),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn active'}  %>
              <% if current_user.present? && current_user.role_id == 1 %>      
                <div class="desc">
                  <%= button_to 'Remove', service_path(service), class: 'btn btn-danger btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %>
                </div>
              <% end %>
              <div class="desc"><%= link_to "Add Cart",'javascript:;',id: "service_#{service.id}", class: " btn-sm add-service-id" %></div>
            </div>
          </div>
        </div>
        <!-- /shop -->  
      <% end %>   
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /SECTION -->
<%= render 'services/service_detail_popup_model', services: @services %>

<script type="text/javascript">
  $(document).ready(function(){
    $(".add-service-id").on('click', function(){
      var service_dashboard_id = $(this).attr('id')
      var service_dashboard_id = service_dashboard_id.split('service_')[1]
      $.ajax({
        url: "<%= carts_path %>",
        type: "POST",
        data: {
          service_dashboard_id: service_dashboard_id
        }
      });
    });
  });
</script>

app/views/shared/_header.html.erb
<!-- HEADER -->
<header>
  <!-- TOP HEADER -->
  <div id="top-header">
    <div class="container">
      <ul class="header-links pull-left">
        <% if current_user.present? %>
          <li><a href=""><i class="fa fa-phone"></i> <%= current_user.name %></a></li>
          <li><a href=""><i class="fa fa-envelope-o"></i> <%= current_user.email %></a></li>
          <% else %>
          <li><a href=""><i class="fa fa-phone"></i>Phone</a></li>
          <li><a href=""><i class="fa fa-envelope-o"></i> Email</a></li>
        <% end %>
      </ul>
      <ul class="header-links pull-right">
        <% if current_user.present? %>
          <li style="float:right"><i class="fa fa-user-o"></i><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li style="float:right"><i class="fa fa-user-o"><%= link_to 'My Account', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <!-- /TOP HEADER -->

  <!-- MAIN HEADER -->
  <div id="header">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- LOGO -->
        <div class="col-md-3">
          <div class="header-logo">
            <a href="" class="logo">
              <img src="/assets/logo.png" alt="">
            </a>
          </div>
        </div>
        <!-- /LOGO -->

        <!-- SEARCH BAR -->
        <div class="col-md-6">
          <div class="header-search">
            <form>              
              <%= form_tag(search_page_path, :method => "get",class: 'navbar-form navbar-left') do %>  
                <div class="input-group">  
                  <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
                  <div class="input-group-btn">  
                    <%= button_tag "search", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
                  </div>  
                </div>  
              <% end %>
            </form>
          </div>
        </div>
        <!-- /SEARCH BAR -->

        <!-- ACCOUNT -->
        <div class="col-md-3 clearfix">
          <div class="header-ctn">
            <!-- Cart -->
            <div class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                <i class="fa fa-shopping-cart"></i>
                <span>Your Cart</span>
                <% if current_user.present? %>
                <div class="qty"><%= @cart.cart_items.count %></div>
                <% end %>
              </a>
              <div class="cart-dropdown">
                <div class="cart-list">
                  <% if current_user.nil? %>
                    <h2>Please login first for adding services </h2>
                  <% end %>

                  <% if @cart_items.nil? || @cart_items.empty? %>
                    <h1> Your Cart is Empty </h1>
                  <% else %>
                  <% current_user.present? && @cart_items.each do |ci| %>
                  <div class="product-widget">
                    <div class="product-img">
                      <!-- <img src="/assets/product01.png" alt=""> --><%= cart_item_dashboard_img(ci) %>
                    </div>
                    <div class="product-body">
                      <h3 class="product-name">Category :<%= ci.service.category.name %></h3>
                      <h3 class="product-name">Service :<%= ci.service.title %></h3>
                      <h4 class="product-price"><span class="qty">price : ₹</span><%= ci.service.price %></h4>
                    </div>
                    <!-- <button class="delete"><i class="fa fa-close"></i></button> -->
                    <%= button_to 'X', cart_path(ci), class: 'add-to-cart-btn delete fa fa-close', method: :delete, data: {confirm: 'Are you sure?'} %>
                  </div>
                  <% end %>
                  <% end %>
                </div>
                <div class="cart-summary">
                  <% if current_user.present? %>
                    <small><%= @cart.cart_items.count %> Item(s) selected</small>
                  <% end %>
                  <h5>SUBTOTAL: $2940.00</h5>
                </div>
                <div class="cart-btns">
                  <%= link_to 'ViewCart', carts_path%>
                  <a href="#">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
                </div>
              </div>
            </div>
            <!-- /Cart -->

            <!-- Menu Toogle -->
            <div class="menu-toggle">
              <a href="#">
                <i class="fa fa-bars"></i>
                <span>Menu</span>
              </a>
            </div>
            <!-- /Menu Toogle -->
          </div>
        </div>
        <!-- /ACCOUNT -->
      </div>
      <!-- row -->
    </div>
    <!-- container -->
  </div>
  <!-- /MAIN HEADER -->
</header>
<!-- /HEADER -->


<!-- NAVIGATION -->
<nav id="navigation">
  <!-- container -->
  <div class="container">
    <!-- responsive-nav -->
    <div id="responsive-nav">
      <!-- NAV -->
      <ul class="main-nav nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <% if current_user.present? && current_user.role_id == 1 %>
          <li><%= link_to "Services", services_path %></li>
          <li><%= link_to 'Add Service', new_service_path%></li>
          <li><%= link_to 'Categories', categories_path%></li>
          <li><%= link_to 'Add Category', new_category_path%></li>
        <% end %>
        <li><%= link_to 'Cart', carts_path%></li>
        <% if current_user.present? && current_user.role_id == 1 %>  
          <li><%= link_to 'Users', panels_path%></li>
         <% end %>        
      </ul>
      <!-- /NAV -->
    </div>
    <!-- /responsive-nav -->
  </div>
  <!-- /container -->
</nav>
<!-- /NAVIGATION -->